### ISSUE TITLE
Whatsie not loading in hidden workspace

### ISSUE THREAD

**Issue by zunder** [Aluxian/Whatsie#120]
* Operating system: Arch Linux
* Whatsie version: 2.0.14-beta

I use i3wm with Arch, where I set Whatsie to launch at start up in a specified workspace. Done that, if I go to that workspace the very first time, it looks like Whatsie is just starting loading. Meaning, that between start up and the time I switch to that workspace in order to check for my messages, Whatsie is actually not running. I think that might being a problem on WhatsApp side, as I tried the same thing with Opera, having same results.

My question is if that is being a known problem and if there is any trick to bypass that?

**Comment by Aluxian** [comment]
It's not something on WhatsApp Web's side, it's either how the OS handles things or how Whatsie works. This is not a known problem, thanks for reporting. I don't know of any tricks, but I'll try to fix this when I have a bit more time.

**Comment by Aluxian** [comment]
Hey, this should be fixed in the latest version. Check for update inside the app or download Whatsie again from https://github.com/Aluxian/Whatsie/releases/tag/v2.0.18

**Comment by alpernebbi** [comment]
I still experience this problem with i3 (on Xubuntu).

My i3 config file has `assign [class="Whatsie"] 10` to launch Whatsie in a specific workspace. 
I launched Whatsie from another workspace in debug mode, waited a few minutes and switched to Whatsie's workspace, but it just started loading then.

Debug log:
[1469183979970.txt](https://github.com/Aluxian/Whatsie/files/377999/1469183979970.txt)

Versions:
```
Whatsie 2.0.18 (618)
Electron 1.2.7
Chromium 51.0.2704.106
```
```
i3 version 4.12-74-gb1d70f2 (2016-06-15, branch "next") © 2009 Michael Stapelberg and contributors
```

**Comment by Aluxian** [comment]
Do you have Chrome or Chromium installed? Does the same happen with it?

**Comment by alpernebbi** [comment]
I just installed Chromium, set `http://web.whatsapp.com/` as the homepage and it does the same.

**Comment by Aluxian** [comment]
Ok, so that's the problem... (Whatsie is based on Chromium). Unfortunately, there's nothing I can do about it.
